### DISCUSSION TITLE
What allowed_origins format can I use in Ory Kratos config?

### DISCUSSION THREAD

**Discussion by tamtakoe** [ory/.github#119] [Q&A]
I'm using this config
```yaml
  public:
    cors:
      allowed_origins:
        - https://*.mysite.com
        - http://127.0.0.1:4100
        - http://127.0.0.1:4200
        - http://127.0.0.1:4300
        - http://127.0.0.1:4400
```
How can I simplify this?
Can I use `http://127.0.0.1:4*` or `http://127.0.0.1:*` or `http://127.0.0.1`? I know you can't (I've tried), but why not? Are there other ways to use some sort of template for ports?
