### DISCUSSION TITLE
oathkeeper /health/ready not found

### DISCUSSION THREAD

**Discussion by ghost** [ory/.github#68] [Q&A]
I feel like I'm missing something obvious here, but after deploying what I figured was a rather tame sample config of oathkeeper, I can't seem to get the pods in kubernetes to become ready.

The specific error is

```
time=2023-07-06T04:13:41Z level=error msg=An error occurred while handling a request audience=application
error=map[message:The requested resource could not be found stack_trace:stack trace could not be recovered
from error type *healthx.swaggerNotReadyStatus] http_request=map[headers:map[accept:*/* connection:close
user-agent:kube-probe/1.27+] host:127.0.0.1 method:GET path:/health/ready query:<nil> remote:10.11.242.173:43818
scheme:http] http_response=map[status_code:503] service_name=ORY Oathkeeper service_version=v0.40.3
```

I'm using version 0.33.4 of the oathkeeper helm chart.

the values.yaml I'm using is below

```
serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456

deployment:
  extraEnv:
    - name: LOG_LEVEL
      value: debug

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
```

anyone have any ideas? I don't need to override the health checks in the base helm chart, do I?
